# Generated by Django 4.1.3 on 2023-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Biology Science', 'Biology Science'), ('Humanities', 'Humanities'), ('Commerce With Computer Application', 'Commerce With Computer Application')], max_length=50)),
                ('job', models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Accountant', 'Accountant'), ('Financial Analyst', 'Financial Analyst'), ('Pharmacy', 'Pharmacy'), ('MBBS', 'MBBS'), ('BBA', 'BBA'), ('LLB', 'LLB'), ('B.COM', 'B.COM'), ('BCA', 'BCA')], max_length=50)),
            ],
        ),
    ]
