# Generated by Django 4.1.3 on 2023-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='job',
            new_name='cource',
        ),
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(choices=[('COMPUTER_SCIENCE', 'COMPUTER_SCIENCE'), ('COMMERCE', 'COMMERCE'), ('BIOLOGY_SCIENCE', 'BIOLOGY_SCIENCE'), ('HUMANITIES', 'HUMANITIES'), ('COMMERCE_WITH_CA', 'COMMERCE_WITH_CA')], max_length=50),
        ),
    ]
