# Generated by Django 4.1.3 on 2023-01-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_rename_job_person_cource_alter_person_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Book',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='DOB',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Email_id',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Exam_pappers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Pen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Purpose',
            field=models.CharField(choices=[('ENQUIRY', 'ENQUIRY'), ('PLACE_ORDER', 'PLACE_ORDER'), ('RETURN', 'RETURN')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cource',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Accountant', 'Accountant'), ('Financial Analyst', 'Financial Analyst'), ('Pharmacy', 'Pharmacy'), ('MBBS', 'MBBS'), ('BBA', 'BBA'), ('LLB', 'LLB'), ('B.COM', 'B.COM'), ('BCA', 'BCA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(choices=[('COMPUTER_SCIENCE', 'COMPUTER_SCIENCE'), ('COMMERCE', 'COMMERCE'), ('BIOLOGY_SCIENCE', 'BIOLOGY_SCIENCE'), ('HUMANITIES', 'HUMANITIES'), ('COMMERCE_WITH_CA', 'COMMERCE_WITH_CA')], max_length=50, null=True),
        ),
    ]
