# Generated by Django 4.1.3 on 2023-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_person_adress_person_age_person_book_person_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Book',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Exam_pappers',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Pen',
            field=models.BooleanField(null=True),
        ),
    ]
