# Generated by Django 4.1.3 on 2023-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_person_book_alter_person_exam_pappers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Book',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Exam_pappers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='Pen',
            field=models.BooleanField(default=False),
        ),
    ]
